name: screenshot_ocr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.16.0
  clipboard: ^3.0.14
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.3
  flutter_local_notifications: ^22.1.0
  flutter_foreground_task: ^10.0.0
  pdf: ^3.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
